# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fe38369fa570bb3e25bfdcf5174061e5afcf5bb344cf34cd8ae6f13144538340f38b417af84b903dfe71c02954dda486fbf451df62bf2714a82a42a66a3d7e2

test:
  secret_key_base: 73cb5cc252077fd807708a9d8fc5f8c45d40dcdaafff9857f0e60dcdc05c84bbc3c94398cf6a4342e501ed5a50fb633c51ca0bee7da2f6b8045c2074b0d61d68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
